version: "3.3"
services:

  backend:
    build:
      context: ./SpringBoot
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - "db"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./React
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - "backend"
    stdin_open: true

  db:
    image: docker.io/bitnami/postgresql:11.18.0
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=projektR
    volumes:
      - 'rest2_postgresql_data:/bitnami/postgresql'

volumes:
  rest2_postgresql_data:
    driver: local
  #docker compose up -d
  #docker container exec -it b51 bash
