version: '3.1'
services:
  mongodb:
    image: mongo:4.4
    ports:
    - "27017:27017"
    environment:
     MONGO_INITDB_ROOT_USERNAME: admin
     MONGO_INITDB_ROOT_PASSWORD: pass


  mongo-express:
    image: mongo-express:0.49.0
    restart: always
    ports:
    - "8081:8081"
    environment:
     ME_CONFIG_MONGODB_PORT: 27017
     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
     ME_CONFIG_MONGODB_ADMINPASSWORD: pass
     ME_CONFIG_MONGODB_SERVER:	mongodb
     ME_CONFIG_BASICAUTH_USERNAME:	admin
     ME_CONFIG_BASICAUTH_PASSWORD:	pass