version: '2'
services:
  rest-postgresql:
    image: docker.io/bitnami/postgresql:11
    networks:
      - iot-platform
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=projektR
    volumes:
      - 'rest_postgresql_data:/bitnami/postgresql'

networks:
  iot-platform:
volumes:
  rest_postgresql_data:
    driver: local
