version: '2'
services:
  rest2-postgresql:
    image: docker.io/bitnami/postgresql:11
    networks:
      - iot-platform
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=bezapodataka
      - POSTGRESQL_DATABASE=projektR
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - 'rest2_postgresql_data:/bitnami/postgresql'

networks:
  iot-platform:
volumes:
  rest2_postgresql_data:
    driver: local
